[programs.devnet]
myepicproject = "14Upd1fY5vaWjkbyair8q9xW7Rftp11sUqRuzKJf15cA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/bray/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"

[test]
startup_wait = 100000